### ISSUE TITLE
not working, no file part in the request error

### ISSUE THREAD

**Issue by aicynide** [based-org/chana-solver#1]

**Comment by skullchap** [comment]
@aicynide can you be more specific where did you stuck? write in more detail

**Comment by aicynide** [comment]
$ ~ curl -X POST -F file="UG7DJX.png" http://localhost:8080/solve

{"error":"No file part in the request"}

**Comment by skullchap** [comment]
@aicynide try to add @ before filename like

$ ~ curl -X POST -F file="@UG7DJX.png" http://localhost:8080/solve

**Comment by aicynide** [comment]
hehe working now.
